VectorCnt = 41
[[records]]
ID = 100
State = 0
M = [ 101, 2000, 102, 2000, 103, 2000, 104, 1000, 105, 1500, 106, 1000, 107, 1500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 101
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 1374, 0, 0, 0, 0, 0, 0, 0, -5934, 0, 0, 0, 0, 0, 5934, 0, 0, 0, 0, 0,]

[[records]]
ID = 101
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 40, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 102
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, -140, 1024, 1164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 102
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 40, 40, 40, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 103
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, -250, 0, 0, 0, 0, 0, 1024, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 103
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 104
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 104
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 60, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 105
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 850, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 105
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 50, 10, 10, 10, 50, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 50
State = 1
M = [ 0, 0, 0, 0, 0, 0, -350, 0, 0, 0, 0, 0, 0, 350, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 50
State = 2
M = [ 10, 10, 10, 10, 10, 10, 30, 10, 10, 10, 10, 10, 10, 30, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 106
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -500, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 106
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 50, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 107
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, -874, 280, -1024, -800, -850, 200, -150, 0, 5934, 0, 0, 0, 0, 0, -5934, 0, 0, 0, 0, 0,]

[[records]]
ID = 107
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 0, 10, 500, 1000, 1000, 1000, 10, 10, 500, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 401
State = 1
M = [ -1374, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -5934, 0, 0, 0, 0, 0, 5934, 0, 0, 0, 0, 0,]

[[records]]
ID = 401
State = 2
M = [ 40, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 402
State = 1
M = [ 0, 140, -1024, -1164, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 402
State = 2
M = [ 10, 40, 40, 40, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 403
State = 1
M = [ 250, 0, 0, 0, 0, 0, -1024, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 403
State = 2
M = [ 10, 10, 10, 10, 10, 10, 0, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 404
State = 1
M = [ 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 404
State = 2
M = [ 10, 10, 10, 10, 10, 10, 50, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 405
State = 1
M = [ -200, 0, 0, 0, -850, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 405
State = 2
M = [ 50, 10, 10, 10, 50, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 406
State = 1
M = [ 0, 0, 0, 600, 0, 0, -150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 406
State = 2
M = [ 10, 10, 10, 40, 10, 10, 30, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 407
State = 1
M = [ 874, -140, 1024, 664, 850, 0, 170, 0, 0, 0, 0, 0, 0, 0, 0, 5934, 0, 0, 0, 0, 0, -5934, 0, 0, 0, 0, 0,]

[[records]]
ID = 407
State = 2
M = [ 30, 30, 30, 30, 30, 10, 0, 10, 10, 10, 10, 10, 10, 10, 10, 500, 1000, 1000, 1000, 10, 10, 500, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 1
State = 1
M = [ 0, 0, 0, -800, 0, 0, 0, 0, 0, 0, 0, 0, 0, -200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 1
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 501
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 2780, -130, 0, 200, 0, 400, 400, 0, -5934, 0, 0, 0, 0, 0, 5934, 0, 0, 0, 0, 0,]

[[records]]
ID = 501
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 60, 60, 10, 60, 10, 60, 5, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 502
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, -700, 0, 0, 400, 0, -600, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 502
State = 2
M = [ 10, 10, 10, 0, 10, 10, 10, 0, 10, 10, 0, 10, 0, 0, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 503
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2967, 0, 0, 0, 0, 0, 2967, 0, 0, 0, 0, 0,]

[[records]]
ID = 503
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 0, 0, 1000, 1000, 1000, 1000, 0, 0,]

[[records]]
ID = -1
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = -1
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

