VectorCnt = 28
[[records]]
ID = 90
State = 0
M = [ 11, 1800, 12, 500, 13, 3000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 95
State = 0
M = [ 11, 1800, 12, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 10
State = 1
M = [ -1374, -880, 1064, 500, 0, -150, 75, 1294, -500, 1024, 1160, 0, -20, -20, 0, -7000, 0, 0, 0, 0, 0, 7000, 0, 0, 0, 0, 0,]

[[records]]
ID = 10
State = 2
M = [ 30, 15, 30, 10, 10, 10, 10, 30, 10, 15, 10, 30, 10, 10, 10, 800, 10, 10, 10, 10, 10, 800, 10, 10, 10, 10, 10,]

[[records]]
ID = 50
State = 1
M = [ 0, 0, 0, 0, 0, 0, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 50
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,]

[[records]]
ID = 12
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 12
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 20
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 742, 0, 0, -1484, 10, -10, -742, 0, 0, 1484, -10, 10,]

[[records]]
ID = 20
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1500, 10, 10, 1000, 1000, 1000, 1500, 10, 10,]

[[records]]
ID = 21
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -742, 0, 0, 1484, -10, 10, 742, 0, 0, -1484, 10, -10,]

[[records]]
ID = 21
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 700, 1000, 1000, 1000, 10, 10, 700, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 22
State = 1
M = [ -20, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 22
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 23
State = 1
M = [ 20, 0, 0, 0, 0, 0, 0, -20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 23
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 51
State = 1
M = [ 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 51
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 11
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 300, 10, 400, 0, 10, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 11
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 30, 10, 40, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 13
State = 1
M = [ 0, 0, 0, 0, 0, 0, 0, 0, -300, -10, -400, 0, -10, -570, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = -1
State = 2
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 30, 10, 40, 10, 10, 10, 10, 1000, 1000, 1000, 1000, 10, 10, 1000, 1000, 1000, 1000, 10, 10,]

[[records]]
ID = 29
State = 3
M = [ 2048, 1848, 2048, 2548, 2048, 2048, 2048, 2048, 2248, 2048, 1548, 2048, 2048, 2048, 2048, 29848, 0, 0, -36986, 2272, 1836, -27848, 0, 0, 34586, 1814, 2282,]

[[records]]
ID = 29
State = 4
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 3000, 3000, 3000, 3000, 40, 40, 3000, 3000, 3000, 3000, 40, 40,]

[[records]]
ID = 31
State = 3
M = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 10, 10, 10, 10,]

[[records]]
ID = 31
State = 4
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 0, 0, 0, 0, 0,]

[[records]]
ID = 30
State = 3
M = [ 2298, 1898, 2048, 2648, 2048, 2048, 2048, 1798, 2198, 2048, 1448, 2048, 2048, 2048, 2048, 24516, 0, 0, -30033, 2295, 1785, -24516, 0, 0, 32033, 1805, 2315,]

[[records]]
ID = 30
State = 4
M = [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 3000, 3000, 3000, 3000, 40, 40, 3000, 3000, 3000, 3000, 40, 40,]

